"""Web-UI configuration for MCP server integrations (`~/.jarvis/mcp.json`).

This mirrors `save_mcp_config()` in bootstrap.py so the same ~15 integrations
that are configurable from the setup wizard can also be toggled and configured
from the Settings page in the web UI, without re-running the wizard.

The on-disk format is unchanged: `~/.jarvis/mcp.json` is a JSON file with a
`mcpServers` dict (Claude Code `.mcp.json`-compatible) plus a `_comment` field.
If `mcpServers` ends up empty after an update, the file is deleted entirely.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

JARVIS_DIR = Path.home() / ".jarvis"
MCP_CONFIG_PATH = JARVIS_DIR / "mcp.json"

# Repo root (parent of the `jarvis` package) — used for the WhatsApp bridge path,
# matching bootstrap.py's `ROOT / "whatsapp-mcp" / "whatsapp-mcp-server"`.
ROOT = Path(__file__).resolve().parents[2]

_COMMENT = (
    "Generated by the JARVIS setup wizard. Format matches Claude Code's .mcp.json. "
    "Edit freely; re-running the wizard will only touch the integrations you toggled."
)


def _field(name: str, label: str, type_: str = "text", required: bool = True, placeholder: str = "") -> dict[str, Any]:
    return {"name": name, "label": label, "type": type_, "required": required, "placeholder": placeholder}


# Each connector entry describes:
#   id              server key used in mcpServers (and the connector id for the API)
#   label           human readable name
#   description     short description
#   category        logical group: communication/knowledge/developer/productivity/lifestyle/infrastructure
#   fields          list of field descriptors (name/label/type/required)
#   available_soon  (optional) true if the MCP implementation is not yet ready — UI shows "Coming soon"
CONNECTORS: list[dict[str, Any]] = [
    # ── Communication ────────────────────────────────────────────────────────
    {
        "id": "whatsapp",
        "label": "WhatsApp",
        "description": "Send and receive WhatsApp messages via a QR-paired bridge.",
        "category": "communication",
        "fields": [],
    },
    {
        "id": "gmail",
        "label": "Gmail",
        "description": "Read and send email via Gmail (OAuth handled on first use).",
        "category": "communication",
        "fields": [],
    },
    {
        "id": "slack",
        "label": "Slack",
        "description": "Read messages from Slack channels, DMs, and group DMs.",
        "category": "communication",
        "fields": [
            _field("slack_token", "Bot Token (xoxb-...)", "password"),
        ],
    },
    {
        "id": "meta-ads",
        "label": "Meta Ads",
        "description": "Manage Meta (Facebook/Instagram) ad campaigns.",
        "category": "communication",
        "fields": [],
    },
    # ── Knowledge ────────────────────────────────────────────────────────────
    {
        "id": "notion",
        "label": "Notion",
        "description": "Read and write Notion pages and databases.",
        "category": "knowledge",
        "fields": [
            _field("notion_token", "Integration Token", "password"),
        ],
    },
    {
        "id": "obsidian",
        "label": "Obsidian",
        "description": "Read notes from your local Obsidian vault.",
        "category": "knowledge",
        "fields": [
            _field("obsidian_vault_path", "Vault Path", "text"),
        ],
        "available_soon": True,
    },
    {
        "id": "gdrive",
        "label": "Google Drive",
        "description": "Access Docs, Sheets, and files from Google Drive (requires Google OAuth setup).",
        "category": "knowledge",
        "fields": [],
        "available_soon": True,
    },
    {
        "id": "todoist",
        "label": "Todoist",
        "description": "Manage tasks and projects in Todoist.",
        "category": "knowledge",
        "fields": [],
    },
    {
        "id": "mem0",
        "label": "Mem0",
        "description": "Long-term memory store via Mem0.",
        "category": "knowledge",
        "fields": [
            _field("mem0_key", "API Key", "password"),
        ],
    },
    # ── Developer ────────────────────────────────────────────────────────────
    {
        "id": "github",
        "label": "GitHub",
        "description": "Manage repos, issues, and pull requests on GitHub.",
        "category": "developer",
        "fields": [
            _field("github_token", "Personal Access Token", "password"),
        ],
    },
    {
        "id": "playwright",
        "label": "Playwright",
        "description": "Automate browser navigation, clicks, and screenshots.",
        "category": "developer",
        "fields": [],
    },
    {
        "id": "exa",
        "label": "Exa",
        "description": "AI-optimised web search via Exa.",
        "category": "developer",
        "fields": [
            _field("exa_key", "API Key", "password"),
        ],
    },
    # ── Productivity ─────────────────────────────────────────────────────────
    {
        "id": "google-calendar",
        "label": "Google Calendar",
        "description": "Read and manage events on Google Calendar.",
        "category": "productivity",
        "fields": [],
    },
    {
        "id": "google-contacts",
        "label": "Google Contacts",
        "description": "Look up people and contact info from Google Contacts (requires Google OAuth).",
        "category": "productivity",
        "fields": [],
        "available_soon": True,
    },
    {
        "id": "google-tasks",
        "label": "Google Tasks",
        "description": "Manage tasks and to-do lists via Google Tasks (shares Google OAuth credentials).",
        "category": "productivity",
        "fields": [],
        "available_soon": True,
    },
    {
        "id": "stripe",
        "label": "Stripe",
        "description": "Manage payments, customers, and subscriptions via Stripe.",
        "category": "productivity",
        "fields": [
            _field("stripe_key", "API Key (Secret Key)", "password"),
        ],
    },
    {
        "id": "revenuecat",
        "label": "RevenueCat",
        "description": "Subscription and revenue analytics via RevenueCat.",
        "category": "productivity",
        "fields": [
            _field("revenuecat_key", "API Key", "password"),
        ],
    },
    {
        "id": "postiz",
        "label": "Postiz",
        "description": "Social media scheduling and posting via Postiz.",
        "category": "productivity",
        "fields": [
            _field("postiz_url", "Postiz URL", "text", required=False, placeholder="http://localhost:5000"),
            _field("postiz_key", "API Key", "password"),
        ],
    },
    # ── Lifestyle ────────────────────────────────────────────────────────────
    {
        "id": "spotify",
        "label": "Spotify",
        "description": "Browse your listening history and playlists via Spotify.",
        "category": "lifestyle",
        "fields": [
            _field("spotify_client_id", "Client ID", "text"),
            _field("spotify_client_secret", "Client Secret", "password"),
        ],
        "available_soon": True,
    },
    {
        "id": "weather",
        "label": "Weather",
        "description": "Fetch current weather conditions and forecasts.",
        "category": "lifestyle",
        "fields": [
            _field("weather_api_key", "OpenWeatherMap API Key", "password", required=False),
        ],
        "available_soon": True,
    },
    {
        "id": "hackernews",
        "label": "Hacker News",
        "description": "Browse top stories and comments from Hacker News.",
        "category": "lifestyle",
        "fields": [],
        "available_soon": True,
    },
    # ── Infrastructure ───────────────────────────────────────────────────────
    {
        "id": "home-assistant",
        "label": "Home Assistant",
        "description": "Control smart-home devices via Home Assistant.",
        "category": "infrastructure",
        "fields": [
            _field("homeassistant_url", "Home Assistant URL", "text", required=False, placeholder="http://homeassistant.local:8123"),
            _field("homeassistant_token", "Long-Lived Access Token", "password"),
        ],
    },
    {
        "id": "elevenlabs",
        "label": "ElevenLabs",
        "description": "High-quality text-to-speech voices via ElevenLabs.",
        "category": "infrastructure",
        "fields": [
            _field("elevenlabs_key", "API Key", "password"),
        ],
    },
]

_CONNECTORS_BY_ID = {c["id"]: c for c in CONNECTORS}


def _mask(value: str) -> str:
    """Mask a secret value, showing only the last 4 characters."""
    if not value:
        return ""
    if len(value) <= 4:
        return "*" * len(value)
    return "*" * (len(value) - 4) + value[-4:]


def _load_config() -> dict[str, Any]:
    if not MCP_CONFIG_PATH.exists():
        return {"mcpServers": {}}
    try:
        data = json.loads(MCP_CONFIG_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {"mcpServers": {}}
    data.setdefault("mcpServers", {})
    return data


def _extract_value(server: dict[str, Any], field_name: str) -> str:
    """Pull a stored field value back out of an mcpServers entry, given the
    field's cfg-key name (e.g. "elevenlabs_key", "postiz_url")."""
    env = server.get("env", {}) or {}
    headers = server.get("headers", {}) or {}
    auth = headers.get("Authorization", "") if isinstance(headers, dict) else ""
    bearer = auth[len("Bearer "):] if auth.startswith("Bearer ") else ""

    if field_name == "elevenlabs_key":
        return env.get("ELEVENLABS_API_KEY", "")
    if field_name == "revenuecat_key":
        return bearer
    if field_name == "postiz_url":
        url = server.get("url", "")
        if "/mcp/" in url:
            return url.split("/mcp/")[0]
        return url
    if field_name == "postiz_key":
        url = server.get("url", "")
        if "/mcp/" in url:
            return url.split("/mcp/", 1)[1]
        return ""
    if field_name == "homeassistant_url":
        url = server.get("url", "")
        suffix = "/mcp_server/sse"
        if url.endswith(suffix):
            return url[: -len(suffix)]
        return url
    if field_name == "homeassistant_token":
        return bearer
    if field_name == "exa_key":
        url = server.get("url", "")
        if "exaApiKey=" in url:
            return url.split("exaApiKey=", 1)[1]
        return ""
    if field_name == "github_token":
        return env.get("GITHUB_PERSONAL_ACCESS_TOKEN", "")
    if field_name == "notion_token":
        return env.get("NOTION_TOKEN", "")
    if field_name == "mem0_key":
        return env.get("MEM0_API_KEY", "")
    if field_name == "stripe_key":
        return bearer
    if field_name == "slack_token":
        return env.get("SLACK_BOT_TOKEN", "")
    if field_name == "obsidian_vault_path":
        args = server.get("args", [])
        # mcp-obsidian: npx -y mcp-obsidian <vault_path>
        if args and len(args) >= 3 and args[1] == "mcp-obsidian":
            return args[-1]
        return ""
    if field_name == "spotify_client_id":
        return env.get("SPOTIFY_CLIENT_ID", "")
    if field_name == "spotify_client_secret":
        return env.get("SPOTIFY_CLIENT_SECRET", "")
    if field_name == "weather_api_key":
        return env.get("OPENWEATHERMAP_API_KEY", "")
    return ""


def get_connectors_status() -> dict[str, Any]:
    """Return status + masked field values for every connector."""
    data = _load_config()
    servers: dict[str, Any] = data.get("mcpServers", {})

    result = []
    for c in CONNECTORS:
        server = servers.get(c["id"])
        enabled = server is not None
        values: dict[str, str] = {}
        for f in c["fields"]:
            raw = _extract_value(server, f["name"]) if enabled else ""
            if f["type"] == "password":
                values[f["name"]] = _mask(raw)
            else:
                values[f["name"]] = raw
        result.append(
            {
                "id": c["id"],
                "label": c["label"],
                "description": c["description"],
                "category": c.get("category", ""),
                "available_soon": c.get("available_soon", False),
                "fields": c["fields"],
                "enabled": enabled,
                "values": values,
            }
        )
    return {"ok": True, "connectors": result}


def _build_server_entry(connector_id: str, fields: dict[str, str]) -> dict[str, Any]:
    """Build the mcpServers entry for *connector_id* from the given (already
    merged with existing values) field values, matching save_mcp_config()."""
    get = lambda name, default="": fields.get(name, default)

    if connector_id == "whatsapp":
        return {
            "command": "uv",
            "args": [
                "--directory",
                str(ROOT / "whatsapp-mcp" / "whatsapp-mcp-server"),
                "run",
                "main.py",
            ],
        }
    if connector_id == "playwright":
        return {"command": "npx", "args": ["-y", "@playwright/mcp@latest"]}
    if connector_id == "gmail":
        return {"command": "npx", "args": ["-y", "@gongrzhe/server-gmail-autoauth-mcp"]}
    if connector_id == "elevenlabs":
        return {
            "command": "uvx",
            "args": ["elevenlabs-mcp"],
            "env": {"ELEVENLABS_API_KEY": get("elevenlabs_key")},
        }
    if connector_id == "revenuecat":
        return {
            "type": "http",
            "url": "https://mcp.revenuecat.ai/mcp",
            "headers": {"Authorization": f"Bearer {get('revenuecat_key')}"},
        }
    if connector_id == "postiz":
        return {
            "type": "http",
            "url": get("postiz_url", "http://localhost:5000") + "/mcp/" + get("postiz_key"),
        }
    if connector_id == "meta-ads":
        return {"type": "http", "url": "https://mcp.facebook.com/ads"}
    if connector_id == "google-calendar":
        return {"command": "npx", "args": ["-y", "@cocal/google-calendar-mcp"]}
    if connector_id == "home-assistant":
        return {
            "type": "http",
            "url": get("homeassistant_url", "http://homeassistant.local:8123") + "/mcp_server/sse",
            "headers": {"Authorization": f"Bearer {get('homeassistant_token')}"},
        }
    if connector_id == "exa":
        return {
            "type": "http",
            "url": f"https://mcp.exa.ai/mcp?exaApiKey={get('exa_key')}",
        }
    if connector_id == "github":
        return {
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-github"],
            "env": {"GITHUB_PERSONAL_ACCESS_TOKEN": get("github_token")},
        }
    if connector_id == "notion":
        return {
            "command": "npx",
            "args": ["-y", "@notionhq/notion-mcp-server"],
            "env": {"NOTION_TOKEN": get("notion_token")},
        }
    if connector_id == "todoist":
        return {"command": "npx", "args": ["-y", "mcp-remote", "https://ai.todoist.net/mcp"]}
    if connector_id == "mem0":
        return {
            "command": "npx",
            "args": ["-y", "@mem0/mcp"],
            "env": {"MEM0_API_KEY": get("mem0_key")},
        }
    if connector_id == "stripe":
        return {
            "type": "http",
            "url": "https://mcp.stripe.com",
            "headers": {"Authorization": f"Bearer {get('stripe_key')}"},
        }
    if connector_id == "slack":
        return {
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-slack"],
            "env": {"SLACK_BOT_TOKEN": get("slack_token")},
        }
    if connector_id == "obsidian":
        return {
            "command": "npx",
            "args": ["-y", "mcp-obsidian", get("obsidian_vault_path")],
        }
    if connector_id == "gdrive":
        return {
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-gdrive"],
        }
    if connector_id == "google-contacts":
        return {
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-google-contacts"],
        }
    if connector_id == "google-tasks":
        return {
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-google-tasks"],
        }
    if connector_id == "spotify":
        return {
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-spotify"],
            "env": {
                "SPOTIFY_CLIENT_ID": get("spotify_client_id"),
                "SPOTIFY_CLIENT_SECRET": get("spotify_client_secret"),
            },
        }
    if connector_id == "weather":
        return {
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-weather"],
            "env": {"OPENWEATHERMAP_API_KEY": get("weather_api_key")},
        }
    if connector_id == "hackernews":
        return {
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-hackernews"],
        }
    raise ValueError(f"unknown connector: {connector_id}")


def update_connector(connector_id: str, enabled: bool, fields: dict[str, Any]) -> None:
    """Enable/disable and configure a single connector, merging into
    `~/.jarvis/mcp.json` the same way save_mcp_config() does for that
    integration.

    `fields` maps cfg-key field names (e.g. "elevenlabs_key") to new values.
    Empty/missing values are treated as "no change" — the existing stored
    value (if any) is preserved, so a masked-and-unchanged secret sent back
    from the frontend doesn't blow away the real value.
    """
    connector = _CONNECTORS_BY_ID.get(connector_id)
    if connector is None:
        raise ValueError(f"unknown connector: {connector_id}")

    data = _load_config()
    servers: dict[str, Any] = data.setdefault("mcpServers", {})

    if enabled:
        existing = servers.get(connector_id)
        merged: dict[str, str] = {}
        for f in connector["fields"]:
            name = f["name"]
            new_value = str(fields.get(name, "") or "").strip()
            if new_value:
                merged[name] = new_value
            elif existing is not None:
                merged[name] = _extract_value(existing, name)
            else:
                merged[name] = ""
        servers[connector_id] = _build_server_entry(connector_id, merged)
    else:
        servers.pop(connector_id, None)

    if not servers:
        if MCP_CONFIG_PATH.exists():
            MCP_CONFIG_PATH.unlink()
        return

    data["_comment"] = _COMMENT
    JARVIS_DIR.mkdir(parents=True, exist_ok=True)
    MCP_CONFIG_PATH.write_text(json.dumps(data, indent=2), encoding="utf-8")
